/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 51f421027f20f12746635401cfe02233)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	ALPHA_ENABLE_PASSWORD_LOGIN: "true";
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALPHA_ENABLE_PASSWORD_LOGIN">> {}
}
