import {backgroundPages,isBackgroundImage} from '@/lib/site-backgrounds';
import {isSameOrigin} from '@/lib/request-origin';
import {getSignedInUser} from '@/lib/auth';
import {database} from '@/db/store';
import {seedUnits,seedProjects,defaultSettings} from '@/lib/catalog';
import {pinId} from '@/lib/plan-funds';
import {copyDefaults} from '@/lib/site-copy';
import {purgeUnusedFiles} from '@/lib/media-storage';
import {z} from 'zod';
const num=z.number().finite().nonnegative();const str=z.string().trim().min(1).max(300);const url=z.string().max(2000).refine(v=>v===''||v.startsWith('/api/files/')||/^https:\/\//.test(v),'URL không hợp lệ');
const backgroundsSchema=z.object(Object.fromEntries(backgroundPages.map(([key])=>[key,z.string().trim().refine(isBackgroundImage,'Ảnh nền không hợp lệ.').optional()]))).strict();
const appearanceSchema=z.object({imageOpacity:z.number().finite().min(0).max(1).optional(),overlayOpacity:z.number().finite().min(0).max(1).optional(),gradientStart:z.string().regex(/^#[\da-f]{6}$/i).optional(),gradientEnd:z.string().regex(/^#[\da-f]{6}$/i).optional()}).strict();
const appearancesSchema=z.object(Object.fromEntries(backgroundPages.map(([key])=>[key,appearanceSchema.optional()]))).strict();
const schemas:Record<string,z.ZodTypeAny>={
unit:z.object({tower:z.string().max(100).optional(),id:str,code:str,projectId:str,category:z.enum(['low','high']),zone:str,type:str,group:str,direction:str,area:num.positive(),builtArea:num,price:num,status:z.enum(['Còn hàng','Đã bán']),beds:num.int(),floor:num.int(),x:num.max(100),y:num.max(100),note:z.string().max(5000),priceTts:z.union([num,z.literal('')]).optional(),priceTttd:z.union([num,z.literal('')]).optional(),priceLoan:z.union([num,z.literal('')]).optional(),totalPrice:z.union([num,z.literal('')]).optional(),pricePerMeter:z.union([num,z.literal('')]).optional(),gift:z.string().max(2000).optional(),policyDate:z.string().max(20).optional(),layoutUrl:url.optional(),posterUrl:url.optional(),sourceLabel:z.string().max(200).optional(),sourceCheckedAt:z.string().datetime().optional(),sourceUrl:url.optional()}),
project:z.object({id:str,name:str,location:str,region:str,developer:str,category:z.enum(['low','high']),status:str,image:z.string().max(500).refine(v=>v===''||v.startsWith('/api/files/')||url.safeParse(v).success,'Ảnh dự án phải là file đã tải lên hoặc đường dẫn hợp lệ.'),hot:z.boolean(),description:z.string().max(20000),lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)}),
customer:z.object({id:str,name:str,phone:z.string().regex(/^[+\d ()-]{8,20}$/),email:z.union([z.literal(''),z.string().email()]),note:z.string().max(5000),stage:z.enum(['Mới','Đang tư vấn','Đã giao dịch'])}),
about:z.object({headline:z.string().max(300),introduction:z.string().max(5000),featuredProjectId:str,featuredTagline:z.string().max(5000),featuredScale:z.string().max(300),selectedProjectIds:z.array(str).max(6).refine(ids=>new Set(ids).size===ids.length,'Dự án gợi ý bị trùng.'),platformTitle:z.string().max(5000),platformBody:z.string().max(5000),journeyTitle:z.string().max(300),newsTitle:z.string().max(300),faq:z.array(z.object({question:str,answer:z.string().trim().min(1).max(5000)})).max(12),contactTitle:z.string().max(5000),contactBody:z.string().max(5000)}),
copy:z.record(z.string(),z.string().max(2000)).refine(o=>Object.keys(o).every(k=>k in copyDefaults),'Nội dung không hợp lệ.'),
guide:z.object({id:str,title:str,body:z.string().trim().min(1).max(20000),order:z.number().int().min(1).max(1000),visible:z.boolean()}),
article:z.object({id:str,title:str,category:str,body:z.string().min(1).max(40000),image:z.string().max(500).refine(v=>v===''||v.startsWith('/api/files/')||url.safeParse(v).success,'Ảnh bài viết phải là file đã tải lên hoặc đường dẫn hợp lệ.'),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}),
settings:z.object({brand:str,phone:z.string().max(30),email:z.union([z.literal(''),z.string().email()]),address:z.string().max(500),holdHours:z.number().int().min(1).max(168),notifications:z.boolean(),profileName:z.string().max(100),logo:url.optional(),alphahubImage:url.optional(),backgrounds:backgroundsSchema.optional(),backgroundAppearance:appearancesSchema.optional()}),
pin:z.object({projectId:str,code:str,layer:z.enum(['plan','map']).optional(),x:num.max(100),y:num.max(100),fund:z.enum(['exc','share','norm']),callout:z.object({x:num.max(100),y:num.max(100)}).optional()}),
favorite:z.object({enabled:z.boolean()}),read:z.object({at:num}),subscription:z.object({email:z.string().email()})};
const contentKinds=new Set(['project','unit','article','about','guide','pin','copy']);
export async function POST(request:Request){try{if(!isSameOrigin(request))return Response.json({error:'Yêu cầu không hợp lệ.'},{status:403});const actor=await getSignedInUser();if(!actor)return Response.json({error:'Vui lòng đăng nhập để lưu dữ liệu.'},{status:401});if(!actor.canEdit)return Response.json({error:'Chỉ tài khoản quản trị được chỉnh sửa.'},{status:403});if(Number(request.headers.get('content-length')||0)>1000000)return Response.json({error:'Dữ liệu quá lớn.'},{status:413});const body:any=await request.json();if(!actor.isAdmin&&!(body.action==='save'&&contentKinds.has(body.kind)||body.action==='import'||body.action==='delete'&&body.kind==='pin'||body.action==='file'||body.action==='deleteFile'))return Response.json({error:'Chỉ tài khoản quản trị được thực hiện thao tác này.'},{status:403});const db=database(),owner='admin',now=Date.now();
const put=(kind:string,id:string,data:unknown)=>db.prepare('INSERT INTO records(owner,kind,id,payload,updated) VALUES(?,?,?,?,?) ON CONFLICT(owner,kind,id) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').bind(owner,kind,id,JSON.stringify(data),now);
const validateUnits=async(items:any[])=>{const projectRows=await db.prepare("SELECT id,payload FROM records WHERE owner=? AND kind='project'").bind(owner).all<any>();const projectMap=new Map(seedProjects.map(p=>[p.id,p]));for(const p of projectRows.results)projectMap.set(p.id,JSON.parse(p.payload));const existing=await db.prepare("SELECT id,payload FROM records WHERE owner=? AND kind='unit'").bind(owner).all<any>();const all=new Map(seedUnits.map(u=>[u.id,u]));for(const u of existing.results)all.set(u.id,JSON.parse(u.payload));for(const u of items){const p=projectMap.get(u.projectId);if(!p||p.category!==u.category)throw Error('Dự án và nhóm sản phẩm của căn chưa khớp.');all.set(u.id,u);}const codes=new Set();for(const u of all.values()){const key=u.projectId+'|'+u.code.trim().toLowerCase();if(codes.has(key))throw Error('Mã căn đã tồn tại trong dự án.');codes.add(key);}for(const u of items){if(u.status==='Đã bán'){const hold=await db.prepare("SELECT id FROM reservations WHERE owner=? AND unit_id=? AND status='Đang giữ chỗ' AND expires_at>? LIMIT 1").bind(owner,u.id,now).first();if(hold)throw Error('Căn đang được giữ chỗ. Hãy chuyển Đã bán trong mục Giao dịch.');}}};
if(body.action==='save'){const {kind}=body;if(!schemas[kind])throw Error('Loại dữ liệu không hợp lệ.');const id=str.parse(body.id);const data=schemas[kind].parse(body.data);if(data.id&&data.id!==id)throw Error('Mã dữ liệu không khớp.');if(['settings','about','copy'].includes(kind)&&id!=='main')throw Error('Cấu hình không hợp lệ.');if(kind==='about'){const rows=await db.prepare("SELECT id FROM records WHERE owner=? AND kind='project'").bind(owner).all<{id:string}>();const ids=new Set([...seedProjects.map(p=>p.id),...rows.results.map(p=>p.id)]);if([data.featuredProjectId,...data.selectedProjectIds].some(projectId=>!ids.has(projectId)))throw Error('Dự án giới thiệu không tồn tại.');}if(kind==='unit')await validateUnits([data]);if(kind==='pin'){if(id!==pinId(data.projectId,data.code,data.layer))throw Error('Mã pin không khớp.');const exists=seedProjects.some(p=>p.id===data.projectId)||await db.prepare("SELECT id FROM records WHERE owner=? AND kind='project' AND id=?").bind(owner,data.projectId).first();if(!exists)throw Error('Dự án không tồn tại.');}const old=['project','article','unit','settings'].includes(kind)?await db.prepare('SELECT payload FROM records WHERE owner=? AND kind=? AND id=?').bind(owner,kind,id).first<{payload:string}>():null;await put(kind,id,data).run();if(old)await purgeUnusedFiles([old.payload]);return Response.json({ok:true});}
if(body.action==='deleteFile'){const id=str.parse(body.id);const used=await purgeUnusedFiles(['/api/files/'+id],true);if(used.length)throw Error('Ảnh đang được dùng (ảnh đại diện, bài viết, căn hoặc cấu hình). Hãy đổi ảnh ở chỗ đó trước.');return Response.json({ok:true});}
if(body.action==='file'){const id=str.parse(body.id);const file=await db.prepare('SELECT id,project_id,kind,mime FROM files WHERE owner=? AND id=?').bind(owner,id).first<{id:string;project_id:string;kind:string;mime:string}>();if(!file)throw Error('Không tìm thấy file trong Thư viện.');
const shared=['site-library','site-backgrounds'].includes(file.project_id);const data=z.object({name:z.string().trim().min(1).max(200),projectId:str,kind:z.enum(['gallery','plan','panorama','model','amenity','document','archived','image','background'])}).parse(body.data);
const pdf=file.mime==='application/pdf';
if(shared?(data.projectId!==file.project_id||![file.kind,'archived'].includes(data.kind)):(['image','background'].includes(data.kind)||pdf!==(data.kind==='document')&&data.kind!=='archived'))throw Error('Loại file không phù hợp.');
if(!shared&&!seedProjects.some(p=>p.id===data.projectId)&&!await db.prepare("SELECT id FROM records WHERE owner=? AND kind='project' AND id=?").bind(owner,data.projectId).first())throw Error('Dự án không tồn tại.');
await db.prepare('UPDATE files SET name=?,project_id=?,kind=? WHERE owner=? AND id=?').bind(data.name,data.projectId,data.kind,owner,id).run();return Response.json({ok:true});}
if(body.action==='delete'){const kind=z.enum(['pin']).parse(body.kind);const id=str.parse(body.id);await db.prepare('DELETE FROM records WHERE owner=? AND kind=? AND id=?').bind(owner,kind,id).run();return Response.json({ok:true});}
if(body.action==='import'){const rows=z.array(schemas.unit).min(1).max(300).parse(body.rows);if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Mã căn bị trùng trong file.');await validateUnits(rows);await db.batch(rows.map(r=>put('unit',r.id,r)));return Response.json({ok:true,count:rows.length});}
if(body.action==='reserve'){const unitId=str.parse(body.unitId),customerId=str.parse(body.customerId),note=z.string().max(5000).parse(body.note||'');const [row,customer,setting]=await Promise.all([db.prepare("SELECT payload FROM records WHERE owner=? AND kind='unit' AND id=?").bind(owner,unitId).first<any>(),db.prepare("SELECT id FROM records WHERE owner=? AND kind='customer' AND id=?").bind(owner,customerId).first(),db.prepare("SELECT payload FROM records WHERE owner=? AND kind='settings' AND id='main'").bind(owner).first<any>()]);const unit=row?JSON.parse(row.payload):seedUnits.find(u=>u.id===unitId);if(!unit||unit.status!=='Còn hàng')return Response.json({error:'Căn không còn khả dụng.'},{status:409});if(!customer)throw Error('Vui lòng chọn khách hàng hợp lệ.');const hours=setting?JSON.parse(setting.payload).holdHours:defaultSettings.holdHours,id=crypto.randomUUID();const result=await db.prepare("INSERT INTO reservations(id,owner,unit_id,customer_id,note,status,expires_at,created_at) SELECT ?,?,?,?,?, 'Đang giữ chỗ',?,? WHERE NOT EXISTS (SELECT 1 FROM reservations WHERE owner=? AND unit_id=? AND (status='Đã bán' OR (status='Đang giữ chỗ' AND expires_at>?))) AND NOT EXISTS (SELECT 1 FROM records WHERE owner=? AND kind='unit' AND id=? AND json_extract(payload,'$.status')='Đã bán')").bind(id,owner,unitId,customerId,note,now+hours*3600000,now,owner,unitId,now,owner,unitId).run();if(!result.meta.changes)return Response.json({error:'Căn vừa được giữ chỗ hoặc đã bán. Hãy tải lại bảng hàng.'},{status:409});await put('notification',id,{title:`Đã giữ chỗ căn ${unit.code}`,at:now}).run();return Response.json({ok:true,id});}
if(body.action==='reservation'){const id=str.parse(body.id),op=z.enum(['cancel','extend','sold']).parse(body.operation);const expiry=24*3600000;const result=await db.prepare("UPDATE reservations SET status=?,expires_at=CASE WHEN ?='extend' THEN expires_at+? ELSE expires_at END WHERE id=? AND owner=? AND status='Đang giữ chỗ' AND expires_at>?").bind(op==='cancel'?'Đã hủy':op==='sold'?'Đã bán':'Đang giữ chỗ',op,expiry,id,owner,now).run();if(!result.meta.changes)return Response.json({error:'Giao dịch đã thay đổi hoặc hết hạn. Vui lòng tải lại.'},{status:409});await put('notification',crypto.randomUUID(),{title:op==='cancel'?'Đã hủy giữ chỗ':op==='sold'?'Đã ghi nhận giao dịch bán':'Đã gia hạn giữ chỗ thêm 24 giờ',at:now}).run();return Response.json({ok:true});}
return Response.json({error:'Thao tác không được hỗ trợ.'},{status:400});}catch(e){console.error(e);return Response.json({error:e instanceof z.ZodError?'Thông tin chưa hợp lệ. Kiểm tra các trường bắt buộc, số và địa chỉ email.':e instanceof Error?e.message:'Không thể lưu. Vui lòng thử lại.'},{status:400});}}
