'use client';
import {useState} from 'react';
import Link from 'next/link';
import {LayoutDashboard,Building2,House,Users,BriefcaseBusiness,Image,FileText,Settings,ExternalLink,LogOut,Menu,X,RefreshCw,ShieldCheck,KeyRound,Info,BookOpen} from 'lucide-react';
import {contentNavigation,publicTabForAdmin,editorSections} from '@/lib/site-navigation';
const contentIcons={ 'gioi-thieu':Info,'du-an':Building2,'quy-hang':House,'tin-tuc':FileText,'huong-dan':BookOpen};
export const adminNavigation=[['tong-quan','Tổng quan',LayoutDashboard],...contentNavigation.map(tab=>[tab.adminSection,tab.label,contentIcons[tab.id]] as const),['khach-hang','Khách hàng',Users],['giao-dich','Giao dịch',BriefcaseBusiness],['thu-vien','Thư viện',Image],['thanh-vien','Tài khoản',KeyRound],['cau-hinh','Cài đặt',Settings]] as const;
export default function AdminShell({section,name,onRefresh,limited=false,role='Quản trị viên'}:{section:string;name:string;onRefresh:()=>void;limited?:boolean;role?:string}){
 const publicTab=publicTabForAdmin(section);
 const [open,setOpen]=useState(false),[error,setError]=useState('');
 return <><aside className={'admin-sidebar '+(open?'is-open':'')}><Link href={limited?'/admin/quan-ly-du-an':'/admin'} className="admin-wordmark"><span>α</span><div>Alpha <b>HUB</b><small>TRUNG TÂM QUẢN TRỊ</small></div></Link><button className="admin-close" aria-label="Đóng menu" onClick={()=>setOpen(false)}><X/></button><div className="admin-nav-label">KHÔNG GIAN LÀM VIỆC</div><nav aria-label="Điều hướng quản trị">{adminNavigation.filter(([id])=>!limited||editorSections.has(id)).map(([id,label,Icon])=><Link aria-current={section===id?'page':undefined} key={id} href={'/admin/'+id} className={section===id?'active':''} onClick={()=>setOpen(false)}><Icon size={19}/>{label}{section===id&&<span className="admin-nav-dot"/>}</Link>)}</nav><div className="admin-side-bottom"><div className="admin-private"><ShieldCheck size={20}/><div>Khu vực quản trị<small>Chỉ tài khoản được cấp quyền</small></div></div><Link href={publicTab?.href||'/quy-hang'} target="_blank" rel="noreferrer"><ExternalLink size={17}/>{publicTab?'Xem trang '+publicTab.label.toLowerCase():'Mở website'}</Link><button onClick={async()=>{try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error();window.location.assign('/dang-nhap');}catch{setError('Chưa đăng xuất được. Vui lòng thử lại.');}}}><LogOut size={17}/>Đăng xuất</button>{error&&<p role="alert">{error}</p>}</div></aside>{open&&<button className="admin-backdrop" aria-label="Đóng điều hướng" onClick={()=>setOpen(false)}/>}<div className="admin-topbar"><div><button className="admin-mobile-toggle" aria-label="Mở điều hướng quản trị" onClick={()=>setOpen(true)}><Menu/></button><span>Không gian quản trị</span><span className="admin-crumb">/ {adminNavigation.find(n=>n[0]===section)?.[1]}</span></div><div className="admin-top-actions">{publicTab&&<Link className="admin-preview-link" href={publicTab.href} target="_blank" rel="noreferrer"><ExternalLink size={16}/><span>Xem ngoài website</span></Link>}<button title="Tải lại dữ liệu" aria-label="Tải lại dữ liệu" onClick={onRefresh}><RefreshCw size={17}/></button><span className="admin-user-avatar">{(name||'A').charAt(0).toUpperCase()}</span><span className="admin-user-name">{name||role}<small>{role}</small></span></div></div></>;
}
