'use client';
import {useState,useMemo,useRef,useEffect} from 'react';
import Link from './site-link';
import {projectPath,resolveProjectTab} from '@/lib/project-routes';
import {Search,Menu,X,ChevronUp,ChevronDown,SlidersHorizontal,LayoutGrid,List,Info,Globe,MapPin,House,Waves,FileText,Images,Building2,Layers,Download,Heart,GitCompareArrows,Maximize,Minimize,Plus,Minus,RotateCcw,ArrowUpRight,Compass,Upload,Map,Check,ChevronLeft,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import Panorama from './panorama';
import type {Project,Unit,Asset} from '@/lib/catalog';
type Props={projects:Project[];project:Project;units:Unit[];assets:Asset[];statusOf:(u:Unit)=>string;onSelect:(u:Unit)=>void;onFavorite:(id:string)=>unknown;favorites:Set<string>;onCompare:(id:string)=>void;compare:string[];exportUnits:(items:Unit[])=>void;initialTab:string;initialMatrix?:boolean;};
const navigation=[['overview','Tổng quan',Info],['vr','Quỹ căn 360°',Globe],['location','Vị trí',MapPin],['zones','Phân khu',Layers],['model','Nhà mẫu',House],['amenity','Tiện ích',Waves],['plan','Mặt bằng',Map],['inventory','Bảng hàng',List],['gallery','Thư viện',Images],['document','Tài liệu',FileText]] as const;
const fmt=(n:number)=>n.toLocaleString('vi-VN',{maximumFractionDigits:3});
function Selector({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tất cả</SelectItem>{values.map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></label>}
export default function ProjectWorkspace({projects,project,units,assets,statusOf,onSelect,onFavorite,favorites,onCompare,compare,exportUnits,initialTab,initialMatrix=false}:Props){
const [tab,setTab]=useState(navigation.some(n=>n[0]===initialTab)?initialTab:'vr'),[search,setSearch]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[dockOpen,setDockOpen]=useState(true),[searchOpen,setSearchOpen]=useState(true),[listOpen,setListOpen]=useState(true),[matrix,setMatrix]=useState(initialMatrix),[zone,setZone]=useState('all'),[type,setType]=useState('all'),[direction,setDirection]=useState('all'),[status,setStatus]=useState('all'),[floor,setFloor]=useState('all'),[tower,setTower]=useState('all'),[price,setPrice]=useState([0,150]),[area,setArea]=useState([0,1000]),[sort,setSort]=useState('code'),[savedOnly,setSavedOnly]=useState(false),[scene,setScene]=useState(0),[zoom,setZoom]=useState(1),[lightbox,setLightbox]=useState<Asset|null>(null),[fullscreen,setFullscreen]=useState(false);
useEffect(()=>{const update=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
const root=useRef<HTMLDivElement>(null);const pano=assets.filter(a=>a.kind==='panorama'),plans=assets.filter(a=>a.kind==='plan');const floors=Array.from(new Set(units.map(u=>u.floor))).sort((a,b)=>b-a);const towers=Array.from(new Set(units.map(u=>u.tower||'Tòa chính')));
const filtered=useMemo(()=>{let data=units.filter(u=>(u.code+' '+u.type+' '+u.zone).toLowerCase().includes(search.toLowerCase())&&(zone==='all'||u.zone===zone)&&(type==='all'||u.type===type)&&(direction==='all'||u.direction===direction)&&(status==='all'||statusOf(u)===status)&&(floor==='all'||String(u.floor)===floor)&&(tower==='all'||(u.tower||'Tòa chính')===tower)&&u.price>=price[0]&&u.price<=price[1]&&u.area>=area[0]&&u.area<=area[1]&&(!savedOnly||favorites.has(u.id)));data.sort((a,b)=>sort==='price-up'?a.price-b.price:sort==='price-down'?b.price-a.price:sort==='area'?b.area-a.area:a.code.localeCompare(b.code));return data;},[units,search,zone,type,direction,status,floor,tower,price,area,sort,savedOnly,favorites,statusOf]);
const title=navigation.find(n=>n[0]===tab)?.[1]||'Dự án';const reset=()=>{setSearch('');setZone('all');setType('all');setDirection('all');setStatus('all');setFloor('all');setTower('all');setPrice([0,150]);setArea([0,1000]);setSavedOnly(false);};
const activeFilters=[zone,type,direction,status,floor,tower].filter(v=>v!=='all').length+(price[0]>0||price[1]<150?1:0)+(area[0]>0||area[1]<1000?1:0)+(savedOnly?1:0);
const changeTab=(v:string,showMatrix=false)=>{window.location.assign(projectPath(project.id,v)+(showMatrix?'?view=floors':''));};

const pictureFiles=tab==='gallery'?[{id:'cover',projectId:project.id,kind:'gallery',name:'Phối cảnh tổng thể',url:project.image},...assets.filter(a=>a.kind==='gallery')]:assets.filter(a=>a.kind===tab);
async function toggleFull(){try{if(document.fullscreenElement){await document.exitFullscreen();setFullscreen(false);}else{await document.documentElement.requestFullscreen();setFullscreen(true);}}catch{toast.error('Thiết bị chưa hỗ trợ chế độ toàn màn hình.');}}
function UnitRows(){return <Table><TableHeader><TableRow>{['Mã căn','Tòa / Tầng','Loại hình','Diện tích','Hướng','Giá (tỷ)','Trạng thái',''].map((t,i)=><TableHead key={i}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(u=><TableRow key={u.id}><TableCell><button className="text-link" onClick={()=>onSelect(u)}>{u.code}</button></TableCell><TableCell>{u.tower||'Tòa chính'} / {u.floor}</TableCell><TableCell>{u.type}</TableCell><TableCell>{fmt(u.area)} m²</TableCell><TableCell>{u.direction}</TableCell><TableCell className="money">{fmt(u.price)}</TableCell><TableCell><span className={'status '+(statusOf(u)==='Còn hàng'?'available':'held')}>{statusOf(u)}</span></TableCell><TableCell><button className="icon-button" aria-label={`So sánh ${u.code}`} onClick={()=>onCompare(u.id)}><GitCompareArrows size={16}/></button></TableCell></TableRow>)}</TableBody></Table>}
function Matrix(){return <div className="floor-board"><div className="floor-board-head"><h3>Sơ đồ chọn căn theo tầng</h3><p>Sắp xếp từ dữ liệu quỹ căn · Không thay thế bản vẽ mặt bằng thực tế.</p></div>{floors.filter(f=>floor==='all'||String(f)===floor).map(f=>{const list=filtered.filter(u=>u.floor===f);return <div className="floor-row" key={f}><span>Tầng <b>{f}</b></span><div>{list.length?list.map(u=><button className={'floor-unit '+(statusOf(u)==='Còn hàng'?'free':'taken')} key={u.id} onClick={()=>onSelect(u)}><strong>{u.code}</strong><span>{u.type} · {u.area} m²</span><b>{fmt(u.price)} tỷ</b></button>):<p>Không có căn phù hợp trên tầng này.</p>}</div></div>})}</div>}
return <div className="project-workspace" ref={root}><div className="workspace-canvas"><img src={project.image} alt={`Phối cảnh ${project.name}`} className="workspace-cover"/><div className="workspace-shade"/></div>
<div className="workspace-top-left"><button className="round-tool" aria-label="Menu dự án" onClick={()=>setMenuOpen(true)}><Menu size={22}/></button><Link className="round-tool" aria-label="Thoát dự án" href="/du-an"><ChevronLeft size={22}/></Link><Link className="workspace-back-label" href="/du-an">Danh sách dự án</Link></div>
<div className="workspace-search-area">{searchOpen&&<div className="workspace-search"><Search size={19}/><input aria-label="Tìm mã căn trong dự án" placeholder="Tìm kiếm mã căn, loại hình, phân khu..." value={search} onChange={e=>{setSearch(e.target.value);setListOpen(true);}}/><button className={'icon-button '+(matrix?'chosen':'')} aria-label="Sơ đồ tầng và căn" onClick={()=>{changeTab('inventory',!matrix);}}><LayoutGrid size={19}/></button><button className="icon-button" aria-label="Bộ lọc dự án" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={19}/>{activeFilters>0&&<sup>{activeFilters}</sup>}</button></div>}<button className="collapse-circle" aria-label={searchOpen?'Thu gọn tìm kiếm':'Mở tìm kiếm'} onClick={()=>setSearchOpen(!searchOpen)}>{searchOpen?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button></div>
<Link href="/du-an" aria-label="Alpha HUB — Danh sách dự án" className="workspace-brand"><img src="/alpha-hub-logo.png" alt="Alpha HUB"/><span>KHÔNG GIAN DỰ ÁN</span></Link>
{['vr','plan'].includes(tab)&&<><div className="scene-caption"><span>{tab==='vr'?'KHÁM PHÁ DỰ ÁN':'MẶT BẰNG SẢN PHẨM'}</span><h1>{project.name}</h1><p><MapPin size={14}/>{project.location}</p></div>{tab==='vr'&&pano.length>0?<div className="immersive-panorama"><Panorama key={pano[scene%pano.length].id} src={pano[scene%pano.length].url}/></div>:tab==='plan'&&plans.length>0?<div className="immersive-plan"><div style={{transform:`scale(${zoom})`}}><img src={plans[scene%plans.length].url} alt="Mặt bằng dự án"/>{filtered.map(u=><button className={'map-pin '+(statusOf(u)==='Còn hàng'?'':'unavailable')} key={u.id} style={{left:`${u.x}%`,top:`${u.y}%`}} onClick={()=>onSelect(u)}>{u.code}</button>)}</div></div>:<div className="scene-message"><span className="scene-symbol">{tab==='vr'?<Globe size={26}/>:<Map size={26}/>}</span><h2>{tab==='vr'?'Toàn cảnh dự án':'Mặt bằng quỹ căn'}</h2><p>{tab==='vr'?'Đang hiển thị phối cảnh tổng thể. Thêm ảnh panorama để xoay và khám phá không gian 360°.':'Chưa có bản vẽ mặt bằng của dự án. Bạn có thể tra cứu vị trí tầng và thông tin căn trong sơ đồ dữ liệu.'}</p><button className="button dark" onClick={()=>{changeTab('inventory',tab==='plan');}}><List size={17}/>{tab==='plan'?'Mở sơ đồ tầng / căn':'Xem bảng hàng'}</button><Link className="button subtle" href={`/thu-vien?project=${encodeURIComponent(project.id)}`}><Upload size={16}/>Thêm {tab==='vr'?'ảnh 360°':'mặt bằng'}</Link></div>}
{listOpen&&<aside className="floating-inventory"><div className="floating-inventory-head"><div><span>QUỸ CĂN DỰ ÁN</span><h2>{filtered.length} sản phẩm</h2></div><button className="icon-button" aria-label="Thu gọn danh sách căn" onClick={()=>setListOpen(false)}><ChevronRight size={18}/></button></div><div className="mini-filter"><button className={status==='all'?'selected':''} onClick={()=>setStatus('all')}>Tất cả</button><button className={status==='Còn hàng'?'selected':''} onClick={()=>setStatus('Còn hàng')}>Còn hàng</button><button aria-label="Lọc danh sách căn" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={15}/></button></div><div className="floating-unit-list">{filtered.map(u=><article key={u.id}><div><button className="mini-unit-code" onClick={()=>onSelect(u)}>{u.code}</button><button className={'icon-button '+(favorites.has(u.id)?'is-favorite':'')} aria-label={`Yêu thích ${u.code}`} onClick={()=>onFavorite(u.id)}><Heart size={16} fill={favorites.has(u.id)?'currentColor':'none'}/></button></div><p>{u.type} · {fmt(u.area)} m² · Tầng {u.floor}</p><div><strong>{fmt(u.price)} <small>tỷ</small></strong><span className={'status '+(statusOf(u)==='Còn hàng'?'available':'held')}>{statusOf(u)}</span></div><button className="mini-detail" onClick={()=>onSelect(u)}>Thông tin căn <ArrowUpRight size={15}/></button></article>)}{!filtered.length&&<div className="workspace-empty"><Search/><h3>Không có căn phù hợp</h3><button className="button subtle" onClick={reset}>Đặt lại bộ lọc</button></div>}</div><div className="floating-foot"><Info size={13}/>{units.some(u=>u.sourceLabel)?'Bảng hàng tham khảo · Chưa đồng bộ trực tiếp':'Quỹ căn và giá minh họa'}</div></aside>}{!listOpen&&<button className="reopen-list button dark" onClick={()=>setListOpen(true)}><List size={17}/>{filtered.length} căn</button>}
{((tab==='vr'&&pano.length>0)||(tab==='plan'&&plans.length>0))&&<div className="scene-picker">{(tab==='vr'?pano:plans).map((s,i)=><button className={scene===i?'active':''} key={s.id} onClick={()=>{setScene(i);setZoom(1);}}><img src={s.url} alt=""/><span>{s.name}</span></button>)}</div>}</>}
{!['vr','plan'].includes(tab)&&<section className="workspace-panel"><div className="workspace-panel-heading"><div><span>{project.name}</span><h1>{title}</h1></div><button className="round-tool" aria-label="Đóng nội dung" onClick={()=>changeTab('vr')}><X size={21}/></button></div><div className="workspace-panel-body">
{tab==='overview'&&<div className="workspace-overview"><div><span className="eyebrow">THÔNG TIN DỰ ÁN</span><h2>{project.name}</h2><p>{project.description}</p><div className="overview-facts">{[['Chủ đầu tư',project.developer],['Địa chỉ',project.location],['Loại hình',project.category==='high'?'Cao tầng':'Thấp tầng'],['Trạng thái',project.status],['Quỹ căn mẫu',units.length],['Còn hàng',units.filter(u=>statusOf(u)==='Còn hàng').length]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="row"><button className="button dark" onClick={()=>changeTab('inventory')}>Xem quỹ căn <ArrowUpRight size={16}/></button><button className="button subtle" onClick={()=>onFavorite(project.id)}><Heart size={16}/>{favorites.has(project.id)?'Đã yêu thích':'Lưu dự án'}</button></div></div><img src={project.image} alt={project.name}/></div>}
{tab==='inventory'&&<><div className="workspace-table-tools"><div className="row"><span className="inventory-total">{filtered.length} căn phù hợp</span><Selector label="Tòa" value={tower} values={towers} onChange={setTower}/><Selector label="Tầng" value={floor} values={floors.map(String)} onChange={setFloor}/><Selector label="Trạng thái" value={status} values={Array.from(new Set(units.map(statusOf)))} onChange={setStatus}/></div><div className="row"><button className="button subtle" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={16}/>Bộ lọc {activeFilters>0&&`(${activeFilters})`}</button><button className="button subtle" onClick={()=>exportUnits(filtered)}><Download size={16}/>Xuất bảng hàng</button><button className="button subtle" onClick={()=>setMatrix(!matrix)}>{matrix?<List size={17}/>:<LayoutGrid size={17}/>} {matrix?'Dạng bảng':'Theo tầng'}</button></div></div><div className="sample-note"><Info size={14}/>{units.some(u=>u.sourceLabel)?'Bảng hàng tham khảo tại thời điểm cập nhật. Giá và trạng thái cần xác nhận lại; chưa đồng bộ trực tiếp.':'Dữ liệu minh họa, chưa kết nối kho hàng chủ đầu tư.'} Nhấn mã căn để xem chi tiết.</div>{matrix?<Matrix/>:<div className="table-wrap"><UnitRows/></div>}{!filtered.length&&<div className="workspace-empty"><h3>Không tìm thấy sản phẩm</h3><button className="button subtle" onClick={reset}>Đặt lại bộ lọc</button></div>}</>}
{tab==='location'&&<div className="workspace-location"><div><MapPin size={36}/><h2>Vị trí dự án</h2><h3>{project.location}</h3><p>Tra cứu vị trí và tuyến đường đến {project.name} trên bản đồ.</p><a className="button dark" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(project.name+' '+project.location)}`}>Mở Google Maps <ArrowUpRight size={17}/></a></div><img src={project.image} alt="Phối cảnh dự án, không phải bản đồ vị trí"/></div>}
{tab==='zones'&&<><p className="muted">Phân khu trong dữ liệu quỹ căn hiện có. Chọn để xem sản phẩm tương ứng.</p><div className="zone-grid">{Array.from(new Set(units.map(u=>u.zone))).map(z=><button key={z} className="zone-card" onClick={()=>{setZone(z);changeTab('inventory');}}><Layers size={28}/><h3>{z}</h3><p>{units.filter(u=>u.zone===z).length} căn · {units.filter(u=>u.zone===z&&statusOf(u)==='Còn hàng').length} căn còn hàng</p><span>Mở bảng hàng <ArrowUpRight size={16}/></span></button>)}</div></>}
{['model','amenity','gallery','document'].includes(tab)&&<><div className="section-heading"><p className="muted">{tab==='document'?'Bảng giá, chính sách và tài liệu gắn với dự án.':tab==='amenity'?'Hình ảnh và thông tin tiện ích được tải lên cho dự án.':tab==='model'?'Khám phá hình ảnh nhà mẫu và không gian nội thất.':'Ảnh tổng thể và thư viện dự án.'}</p><Link className="button subtle" href={`/thu-vien?project=${encodeURIComponent(project.id)}`}><Upload size={16}/>Thêm nội dung</Link></div><div className="workspace-gallery">{pictureFiles.map(a=><article key={a.id}>{tab==='document'?<a href={a.url+'?download=1'}><FileText size={45}/><strong>{a.name}</strong><span>Tải tài liệu <Download size={16}/></span></a>:<button onClick={()=>setLightbox(a)}><img src={a.url} alt={a.name}/><span>{a.name}<Maximize size={16}/></span></button>}</article>)}</div>{!pictureFiles.length&&<div className="workspace-empty"><Upload size={32}/><h3>Chưa có {title.toLowerCase()} được tải lên</h3><p>Thêm tài liệu của dự án tại Thư viện để hiển thị tại đây.</p><Link href={`/thu-vien?project=${encodeURIComponent(project.id)}`} className="button dark">Mở thư viện quản trị</Link></div>}</>}
</div></section>}
<div className="workspace-side-tools"><button className="round-tool" onClick={toggleFull} aria-label="Toàn màn hình">{fullscreen?<Minimize size={19}/>:<Maximize size={19}/>}</button>{tab==='plan'&&plans.length>0&&<><button className="round-tool" aria-label="Phóng to mặt bằng" onClick={()=>setZoom(Math.min(3,zoom+.25))}><Plus size={18}/></button><button className="round-tool" aria-label="Thu nhỏ mặt bằng" onClick={()=>setZoom(Math.max(.5,zoom-.25))}><Minus size={18}/></button><button className="round-tool" aria-label="Đặt lại mặt bằng" onClick={()=>setZoom(1)}><RotateCcw size={18}/></button></>}<button className="round-tool" aria-label="Chia sẻ dự án" onClick={()=>navigator.clipboard.writeText(window.location.origin+'/du-an/'+project.id).then(()=>toast.success('Đã sao chép liên kết dự án.')).catch(()=>toast.error('Không thể sao chép liên kết.'))}><ArrowUpRight size={19}/></button></div>
<div className="workspace-bottom"><button className="collapse-circle" aria-label={dockOpen?'Thu gọn menu dự án':'Mở thanh chức năng'} onClick={()=>setDockOpen(!dockOpen)}>{dockOpen?<ChevronDown size={17}/>:<ChevronUp size={17}/>}</button>{dockOpen&&<nav aria-label="Các mục của dự án" className="workspace-dock">{navigation.map(([v,l,Icon])=><Link key={v} href={projectPath(project.id,v)} data-slot="tabs-trigger" data-state={tab===v?'active':'inactive'} aria-current={tab===v?'page':undefined}><Icon size={22}/><span>{l}</span></Link>)}</nav>}</div>
<Sheet open={filtersOpen} onOpenChange={setFiltersOpen}><SheetContent className="workspace-filter-sheet"><SheetHeader><SheetTitle>Bộ lọc quỹ căn</SheetTitle><SheetDescription>{project.name} · {filtered.length} căn phù hợp</SheetDescription></SheetHeader><div className="sheet-body stack"><Selector label="Phân khu" value={zone} onChange={setZone} values={Array.from(new Set(units.map(u=>u.zone)))}/><Selector label="Loại hình" value={type} onChange={setType} values={Array.from(new Set(units.map(u=>u.type)))}/><Selector label="Hướng" value={direction} onChange={setDirection} values={Array.from(new Set(units.map(u=>u.direction)))}/><Selector label="Trạng thái" value={status} onChange={setStatus} values={Array.from(new Set(units.map(statusOf)))}/><Selector label="Tòa" value={tower} onChange={setTower} values={towers}/><Selector label="Tầng" value={floor} onChange={setFloor} values={floors.map(String)}/><label className="field"><span>Giá: {fmt(price[0])} – {fmt(price[1])} tỷ</span><Slider aria-label="Khoảng giá dự án" min={0} max={150} value={price} step={.1} onValueChange={setPrice}/></label><label className="field"><span>Diện tích: {area[0]} – {area[1]} m²</span><Slider aria-label="Khoảng diện tích dự án" min={0} max={1000} value={area} onValueChange={setArea}/></label><label className="row"><Checkbox checked={savedOnly} onCheckedChange={v=>setSavedOnly(v===true)}/>Chỉ xem căn yêu thích</label><label className="field"><span>Sắp xếp</span><Select value={sort} onValueChange={setSort}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['code','Theo mã căn'],['price-up','Giá tăng dần'],['price-down','Giá giảm dần'],['area','Diện tích giảm dần']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><div className="row"><button className="button subtle" onClick={reset}><RotateCcw size={16}/>Đặt lại</button><button className="button dark" onClick={()=>{setFiltersOpen(false);setListOpen(true);}}>Xem {filtered.length} căn</button></div></div></SheetContent></Sheet>
<Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent side="left"><SheetHeader><img className="workspace-menu-logo" src="/alpha-hub-logo.png" alt="Alpha HUB"/><SheetTitle>{project.name}</SheetTitle><SheetDescription>{project.location}</SheetDescription></SheetHeader><nav className="workspace-menu-links">{navigation.map(([v,l,Icon])=><Link key={v} href={projectPath(project.id,v)} aria-current={tab===v?'page':undefined} className={tab===v?'active':''}><Icon size={19}/>{l}<ChevronRight size={16}/></Link>)}<Link href="/du-an"><ChevronLeft size={17}/>Danh sách dự án</Link><h3>Chuyển dự án</h3>{projects.map(p=><Link key={p.id} href={projectPath(p.id)} className={p.id===project.id?'active':''}><Building2 size={17}/>{p.name}</Link>)}</nav></SheetContent></Sheet>
<Dialog open={!!lightbox} onOpenChange={v=>{if(!v)setLightbox(null);}}><DialogContent className="workspace-lightbox"><DialogHeader><DialogTitle>{lightbox?.name}</DialogTitle><DialogDescription>{project.name}</DialogDescription></DialogHeader>{lightbox&&<><img src={lightbox.url} alt={lightbox.name}/><a className="button subtle" href={lightbox.url} target="_blank" rel="noreferrer">Mở ảnh gốc <ArrowUpRight size={17}/></a></>}</DialogContent></Dialog>
</div>;
}
