'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Phone,Send,Sparkles,ArrowUpRight,Building2,Headphones} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ContactForm from './contact-form';
import Link from './site-link';
import {projectPath} from '@/lib/project-routes';
import type {Project,Unit} from '@/lib/catalog';
type Reply={role:'user'|'assistant';text:string;links?:{label:string;href:string}[]};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
const money=(n:number)=>n.toLocaleString('vi-VN',{maximumFractionDigits:3});
export default function ProjectChatWidget({projects,units,phone,projectId,statusOf}:{projects:Project[];units:Unit[];phone:string;projectId?:string;statusOf:(u:Unit)=>string}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(projectId||''),[input,setInput]=useState(''),[contact,setContact]=useState(false);
 const [messages,setMessages]=useState<Reply[]>([{role:'assistant',text:'Chào bạn! Tôi là trợ lý tra cứu Alpha HUB. Bạn muốn xem dự án nào, tìm mã căn hay tra giá? Tôi sử dụng dữ liệu đang có trên website.'}]);
 const bottom=useRef<HTMLDivElement>(null);const digits=phone.replace(/\D/g,'');const hasPhone=digits.length>=8&&digits.length<=15;const chosen=projects.find(p=>p.id===selected);
 useEffect(()=>{if(projectId)setSelected(projectId);},[projectId]);
 useEffect(()=>{if(open)bottom.current?.scrollIntoView({block:'nearest'});},[messages,open,contact]);
 const reply=(question:string)=>{
  const text=question.trim().slice(0,500);if(!text)return;setInput('');setContact(false);const q=normalize(text);let scope=chosen;
  const direct=projects.find(p=>q.includes(normalize(p.name))||q.includes(normalize(p.id).replaceAll('-',' ')));if(direct){scope=direct;setSelected(direct.id);}
  const exact=units.find(u=>q.includes(normalize(u.code)));let answer:Reply;
  if(exact){const p=projects.find(p=>p.id===exact.projectId);answer={role:'assistant',text:`${exact.code} · ${p?.name||''}\n${exact.type} · ${money(exact.area)} m² · ${exact.direction}\nGiá tham khảo: ${money(exact.price)} tỷ. Trạng thái trên website: ${statusOf(exact)}.`,links:[{label:'Xem chi tiết căn',href:projectPath(exact.projectId)+'?product='+encodeURIComponent(exact.code)}]};}
  else if(/lien he|hotline|zalo|tu van|nhan vien/.test(q)){setContact(true);answer={role:'assistant',text:hasPhone?`Bạn có thể gọi ${phone}, mở Zalo hoặc để lại thông tin bên dưới để được tư vấn.`:'Hotline/Zalo đang được cập nhật. Bạn có thể gửi yêu cầu tư vấn bên dưới.'};}
  else if(scope){const all=units.filter(u=>u.projectId===scope.id);const budget=q.match(/(?:duoi|toi da|tam|khoang|ngan sach)\s*(\d+(?:[.,]\d+)?)\s*(?:ty|ti)/);const max=budget?Number(budget[1].replace(',','.')):null;const available=all.filter(u=>statusOf(u)==='Còn hàng'&&(max===null||u.price<=max));const prices=all.map(u=>u.price).filter(n=>n>0);answer={role:'assistant',text:`${scope.name}\n${scope.location}\nWebsite có ${all.length} căn, ${all.filter(u=>statusOf(u)==='Còn hàng').length} căn đang hiển thị còn hàng.${prices.length?` Giá tham khảo từ ${money(Math.min(...prices))} đến ${money(Math.max(...prices))} tỷ.`:''}${max!==null?`\nCó ${available.length} căn còn hàng với giá không quá ${money(max)} tỷ.`:''}\nGiá và trạng thái cần xác nhận lại với tư vấn viên.`,links:[{label:'Mở bảng hàng dự án',href:projectPath(scope.id,'inventory')},...available.slice(0,3).map(u=>({label:`${u.code} · ${money(u.price)} tỷ`,href:projectPath(u.projectId)+'?product='+encodeURIComponent(u.code)}))]};}
  else{const words=q.split(/\s+/).filter(w=>w.length>2&&!['xem','gia','can','tim','cho','toi','bao','nhieu','duoi','tren'].includes(w));const matching=projects.filter(p=>words.some(w=>normalize(p.name+' '+p.location).includes(w)));const options=matching.length?matching:projects.slice(0,4);answer={role:'assistant',text:'Hãy chọn dự án phía trên để tra giá và quỹ căn, hoặc nhập mã căn cụ thể. Một số dự án bạn có thể xem:',links:options.slice(0,5).map(p=>({label:`${p.name} · ${units.filter(u=>u.projectId===p.id).length} căn`,href:projectPath(p.id,'inventory')}))};}
  setMessages(prev=>[...prev.slice(-28),{role:'user',text},answer]);
 };
 const missingContact=()=>{setOpen(true);setContact(true);};
 return <><div className="project-contact-dock" aria-label="Liên hệ và tư vấn"><button className="dock-chat" onClick={()=>setOpen(true)} aria-label="Mở chatbot dự án" title="Chatbot dự án"><MessageCircle size={26}/><i/></button>{hasPhone?<a className="dock-zalo" href={'https://zalo.me/'+digits} target="_blank" rel="noreferrer" aria-label="Liên hệ Zalo" title="Chat Zalo">Zalo</a>:<button className="dock-zalo" onClick={missingContact} aria-label="Liên hệ Zalo" title="Liên hệ Zalo">Zalo</button>}{hasPhone?<a className="dock-phone" href={'tel:+'+(digits.startsWith('0')?'84'+digits.slice(1):digits)} aria-label={`Gọi hotline ${phone}`} title={phone}><Phone size={23}/></a>:<button className="dock-phone" onClick={missingContact} aria-label="Gọi hotline" title="Hotline"><Phone size={23}/></button>}</div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="project-chat-panel"><header className="project-chat-header"><span className="chat-avatar"><Sparkles size={24}/></span><div><DialogTitle>Trợ lý dự án Alpha HUB</DialogTitle><DialogDescription>Tra cứu nhanh · Kết nối tư vấn</DialogDescription></div></header><div className="project-chat-selector"><Building2 size={17}/><select aria-label="Dự án cần tư vấn" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Chọn dự án bạn quan tâm</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="project-chat-messages" role="log" aria-live="polite" aria-label="Nội dung trò chuyện">{messages.map((m,i)=><div className={'chat-message '+m.role} key={i}><p>{m.text}</p>{m.links&&<div className="chat-result-links">{m.links.map(l=><Link key={l.href} href={l.href}>{l.label}<ArrowUpRight size={14}/></Link>)}</div>}</div>)}{contact&&<div className="chat-contact-form"><h3><Headphones size={17}/>Yêu cầu tư vấn</h3><p>{hasPhone?`Hotline: ${phone}`:'Số Hotline/Zalo chưa được quản trị viên cập nhật.'}</p>{hasPhone&&<div className="chat-direct-links"><a href={'tel:'+phone}>Gọi Hotline</a><a href={'https://zalo.me/'+digits} target="_blank" rel="noreferrer">Mở Zalo</a></div>}<ContactForm note={chosen?`Yêu cầu từ chatbot: ${chosen.name}`:'Yêu cầu tư vấn từ chatbot dự án'}/></div>}<div ref={bottom}/></div><div className="project-chat-quick">{['Xem quỹ căn','Giá dự án','Liên hệ tư vấn'].map(q=><button key={q} onClick={()=>reply(q)}>{q}</button>)}</div><form className="project-chat-compose" onSubmit={e=>{e.preventDefault();reply(input);}}><input aria-label="Câu hỏi cho chatbot" placeholder={chosen?'Ví dụ: căn dưới 5 tỷ, hoặc mã căn...':'Nhập tên dự án hoặc mã căn...'} value={input} onChange={e=>setInput(e.target.value)} maxLength={500}/><button type="submit" disabled={!input.trim()} aria-label="Gửi câu hỏi"><Send size={19}/></button></form><p className="project-chat-footnote">Trợ lý tra cứu tự động, không phải nhân viên trực tuyến.</p></DialogContent></Dialog></>;
}
