'use client';
import {useState,useMemo,useRef,useEffect} from 'react';
import Link from './site-link';
import {projectPath,resolveProjectTab} from '@/lib/project-routes';
import {Search,Menu,X,ChevronUp,ChevronDown,SlidersHorizontal,LayoutGrid,List,Info,Globe,MapPin,House,Waves,FileText,Images,Building2,Layers,Download,Heart,GitCompareArrows,Maximize,Minimize,Plus,Minus,RotateCcw,ArrowUpRight,Compass,Upload,Map,Check,ChevronLeft,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import Panorama from './panorama';
import PlanBoard from './plan-board';
import {usePublicContact} from './public-contact-provider';
import type {Project,Unit,Asset} from '@/lib/catalog';
import {pinLayer,type UnitPin} from '@/lib/plan-funds';
type Props={canManage?:boolean;sourceStatus?:string;projects:Project[];project:Project;units:Unit[];assets:Asset[];pins?:UnitPin[];onReload?:()=>void;statusOf:(u:Unit)=>string;onSelect:(u:Unit)=>void;onFavorite:(id:string)=>unknown;favorites:Set<string>;onCompare:(id:string)=>void;compare:string[];exportUnits:(items:Unit[])=>void;initialTab:string;initialMatrix?:boolean;};
const navigation=[['overview','Tổng quan',Info],['vr','Quỹ căn 360°',Globe],['location','Vị trí',MapPin],['zones','Phân khu',Layers],['model','Nhà mẫu',House],['amenity','Tiện ích',Waves],['plan','Mặt bằng',Map],['unitplan','Mặt Bằng Căn',LayoutGrid],['inventory','Bảng hàng',List],['gallery','Thư viện',Images],['document','Tài liệu',FileText]] as const;
const fmt=(n:number)=>n.toLocaleString('vi-VN',{maximumFractionDigits:3});
function Selector({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tất cả</SelectItem>{values.map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></label>}
export default function ProjectWorkspace({canManage=false,sourceStatus,projects,project,units,assets,pins=[],onReload=()=>{},statusOf,onSelect,onFavorite,favorites,onCompare,compare,exportUnits,initialTab,initialMatrix=false}:Props){
const contact=usePublicContact();
const nav=navigation.filter(n=>n[0]!=='unitplan'||project.id==='green-paradise');
const [tab,setTab]=useState(navigation.some(n=>n[0]===initialTab)?initialTab:'vr'),[search,setSearch]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[dockOpen,setDockOpen]=useState(true),[searchOpen,setSearchOpen]=useState(true),[listOpen,setListOpen]=useState(true),[matrix,setMatrix]=useState(initialMatrix),[zone,setZone]=useState('all'),[type,setType]=useState('all'),[direction,setDirection]=useState('all'),[status,setStatus]=useState('all'),[floor,setFloor]=useState('all'),[tower,setTower]=useState('all'),[price,setPrice]=useState([0,150]),[area,setArea]=useState([0,1000]),[sort,setSort]=useState('code'),[savedOnly,setSavedOnly]=useState(false),[scene,setScene]=useState(0),[zoom,setZoom]=useState(1),[lightbox,setLightbox]=useState<Asset|null>(null),[fullscreen,setFullscreen]=useState(false);
useEffect(()=>{const update=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
const isGreen=project.id==='green-paradise';
const mapPins=pins.filter(p=>pinLayer(p)==='map'),planPins=pins.filter(p=>pinLayer(p)==='plan');const usePlanBoard=isGreen||planPins.length>0||canManage;
const root=useRef<HTMLDivElement>(null);const pano=assets.filter(a=>a.kind==='panorama'),plans=assets.filter(a=>a.kind==='plan');const floors=Array.from(new Set(units.map(u=>u.floor))).sort((a,b)=>b-a);const towers=Array.from(new Set(units.map(u=>u.tower||'Tòa chính')));
const filtered=useMemo(()=>{let data=units.filter(u=>(u.code+' '+u.type+' '+u.zone).toLowerCase().includes(search.toLowerCase())&&(zone==='all'||u.zone===zone)&&(type==='all'||u.type===type)&&(direction==='all'||u.direction===direction)&&(status==='all'||statusOf(u)===status)&&(floor==='all'||String(u.floor)===floor)&&(tower==='all'||(u.tower||'Tòa chính')===tower)&&u.price>=price[0]&&u.price<=price[1]&&u.area>=area[0]&&u.area<=area[1]&&(!savedOnly||favorites.has(u.id)));data.sort((a,b)=>sort==='price-up'?a.price-b.price:sort==='price-down'?b.price-a.price:sort==='area'?b.area-a.area:a.code.localeCompare(b.code));return data;},[units,search,zone,type,direction,status,floor,tower,price,area,sort,savedOnly,favorites,statusOf]);
const visibleCodes=useMemo(()=>new Set(filtered.map(u=>u.code.toUpperCase())),[filtered]);const vrScenes:Asset[]=[...plans,{id:'map',projectId:project.id,kind:'map',name:'Phối cảnh dự án',url:project.image},...pano];const vrScene=vrScenes[scene%vrScenes.length];
const title=navigation.find(n=>n[0]===tab)?.[1]||'Dự án';const reset=()=>{setSearch('');setZone('all');setType('all');setDirection('all');setStatus('all');setFloor('all');setTower('all');setPrice([0,150]);setArea([0,1000]);setSavedOnly(false);};
const activeFilters=[zone,type,direction,status,floor,tower].filter(v=>v!=='all').length+(price[0]>0||price[1]<150?1:0)+(area[0]>0||area[1]<1000?1:0)+(savedOnly?1:0);
const changeTab=(v:string,showMatrix=false)=>{window.location.assign(projectPath(project.id,v)+(showMatrix?'?view=floors':''));};
const openUnit=(u:Unit)=>{if(isGreen)window.location.assign(`${projectPath(project.id,'vr')}?product=${encodeURIComponent(u.code)}`);else onSelect(u);};

const pictureFiles=tab==='gallery'?[{id:'cover',projectId:project.id,kind:'gallery',name:'Phối cảnh tổng thể',url:project.image},...assets.filter(a=>a.kind==='gallery')]:assets.filter(a=>a.kind===tab);
async function toggleFull(){try{if(document.fullscreenElement){await document.exitFullscreen();setFullscreen(false);}else{await document.documentElement.requestFullscreen();setFullscreen(true);}}catch{toast.error('Thiết bị chưa hỗ trợ chế độ toàn màn hình.');}}
function UnitRows(){return <Table><TableHeader><TableRow>{['Mã căn','Tòa / Tầng','Loại hình','Diện tích','Hướng','Giá (tỷ)','Trạng thái',''].map((t,i)=><TableHead key={i}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(u=><TableRow key={u.id}><TableCell><button className="text-link" onClick={()=>openUnit(u)}>{u.code}</button></TableCell><TableCell>{u.tower||'Tòa chính'} / {u.floor}</TableCell><TableCell>{u.type}</TableCell><TableCell>{fmt(u.area)} m²</TableCell><TableCell>{u.direction}</TableCell><TableCell className="money">{fmt(u.price)}</TableCell><TableCell><span className={'status '+(statusOf(u)==='Còn hàng'?'available':'held')}>{statusOf(u)}</span></TableCell><TableCell><button className="icon-button" aria-label={`So sánh ${u.code}`} onClick={()=>onCompare(u.id)}><GitCompareArrows size={16}/></button></TableCell></TableRow>)}</TableBody></Table>}
function Matrix(){return <div className="floor-board"><div className="floor-board-head"><h3>Sơ đồ chọn căn theo tầng</h3><p>Sắp xếp từ dữ liệu quỹ căn · Không thay thế bản vẽ mặt bằng thực tế.</p></div>{floors.filter(f=>floor==='all'||String(f)===floor).map(f=>{const list=filtered.filter(u=>u.floor===f);return <div className="floor-row" key={f}><span>Tầng <b>{f}</b></span><div>{list.length?list.map(u=><button className={'floor-unit '+(statusOf(u)==='Còn hàng'?'free':'taken')} key={u.id} onClick={()=>openUnit(u)}><strong>{u.code}</strong><span>{u.type} · {u.area} m²</span><b>{fmt(u.price)} tỷ</b></button>):<p>Không có căn phù hợp trên tầng này.</p>}</div></div>})}</div>}
return <div className="project-workspace" ref={root}><div className="workspace-canvas"><img src={project.image} alt={`Phối cảnh ${project.name}`} className="workspace-cover"/><div className="workspace-shade"/></div>
<div className="workspace-top-left"><button className="round-tool" aria-label="Menu dự án" onClick={()=>setMenuOpen(true)}><Menu size={22}/></button><Link className="round-tool" aria-label="Thoát dự án" href="/du-an"><ChevronLeft size={22}/></Link><Link className="workspace-back-label" href="/du-an">Danh sách dự án</Link></div>
<div className="workspace-search-area">{searchOpen&&<div className="workspace-search"><Search size={19}/><input aria-label="Tìm mã căn trong dự án" placeholder="Tìm kiếm mã căn, loại hình, phân khu..." value={search} onChange={e=>{setSearch(e.target.value);setListOpen(true);}}/><button className={'icon-button '+(matrix?'chosen':'')} aria-label="Sơ đồ tầng và căn" onClick={()=>{changeTab('inventory',!matrix);}}><LayoutGrid size={19}/></button><button className="icon-button" aria-label="Bộ lọc dự án" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={19}/>{activeFilters>0&&<sup>{activeFilters}</sup>}</button></div>}<button className="collapse-circle" aria-label={searchOpen?'Thu gọn tìm kiếm':'Mở tìm kiếm'} onClick={()=>setSearchOpen(!searchOpen)}>{searchOpen?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button></div>
<Link href="/du-an" aria-label="Alpha HUB — Danh sách dự án" className="workspace-brand"><img src={contact.logo} alt="Alpha HUB"/><span>KHÔNG GIAN DỰ ÁN</span></Link>
{['vr','plan'].includes(tab)&&<><div className="scene-caption"><span>{tab==='vr'?'KHÁM PHÁ DỰ ÁN':'MẶT BẰNG SẢN PHẨM'}</span><h1>{project.name}</h1><p><MapPin size={14}/>{project.location}</p></div>{tab==='vr'&&vrScene.kind==='panorama'?<div className="immersive-panorama"><Panorama key={vrScene.id} src={vrScene.url}/></div>:tab==='vr'&&vrScene.kind==='plan'?<div className="immersive-map"><PlanBoard key={'vr-'+vrScene.id} chrome="map" projectId={project.id} layer="plan" image={vrScene.url} units={units} pins={planPins} canManage={canManage} statusOf={statusOf} visibleCodes={visibleCodes} onOpenUnit={openUnit} onSaved={onReload}/></div>:tab==='vr'?<div className="immersive-map"><PlanBoard key="map" projectId={project.id} layer="map" image={project.image} units={units} pins={mapPins} canManage={canManage} statusOf={statusOf} visibleCodes={visibleCodes} onOpenUnit={openUnit} onSaved={onReload}/></div>:tab==='plan'&&plans.length>0?(usePlanBoard?<div className="immersive-plan"><PlanBoard key={plans[scene%plans.length].id} projectId={project.id} layer="plan" image={plans[scene%plans.length].url} units={units} pins={planPins} canManage={canManage} statusOf={statusOf} visibleCodes={visibleCodes} onOpenUnit={openUnit} onSaved={onReload}/></div>:<div className="immersive-plan"><div style={{transform:`scale(${zoom})`}}><img src={plans[scene%plans.length].url} alt="Mặt bằng dự án"/>{filtered.map(u=><button className={'map-pin '+(statusOf(u)==='Còn hàng'?'':'unavailable')} key={u.id} style={{left:`${u.x}%`,top:`${u.y}%`}} onClick={()=>openUnit(u)}>{u.code}</button>)}</div></div>):<div className="scene-message"><span className="scene-symbol">{tab==='vr'?<Globe size={26}/>:<Map size={26}/>}</span><h2>{tab==='vr'?'Toàn cảnh dự án':'Mặt bằng quỹ căn'}</h2><p>{tab==='vr'?'Chọn một căn trong quỹ căn bên phải để mở bản vẽ và thông tin chi tiết.':'Chưa có bản vẽ mặt bằng của dự án. Bạn có thể tra cứu vị trí tầng và thông tin căn trong sơ đồ dữ liệu.'}</p><button className="button dark" onClick={()=>{if(isGreen)setListOpen(true);else changeTab('inventory',tab==='plan');}}><List size={17}/>{isGreen&&tab==='vr'?'Mở quỹ căn':tab==='plan'?'Mở sơ đồ tầng / căn':'Xem bảng hàng'}</button>{canManage&&<Link className="button subtle" href={`/admin/thu-vien?project=${encodeURIComponent(project.id)}`}><Upload size={16}/>Thêm {tab==='vr'?'ảnh 360°':'mặt bằng'}</Link>}</div>}
{listOpen&&<aside className="floating-inventory"><div className="floating-inventory-head"><div><span>QUỸ CĂN DỰ ÁN</span><h2>{filtered.length} sản phẩm</h2></div><button className="icon-button" aria-label="Thu gọn danh sách căn" onClick={()=>setListOpen(false)}><ChevronRight size={18}/></button></div><div className="mini-filter"><button className={status==='all'?'selected':''} onClick={()=>setStatus('all')}>Tất cả</button><button className={status==='Còn hàng'?'selected':''} onClick={()=>setStatus('Còn hàng')}>Còn hàng</button><button aria-label="Lọc danh sách căn" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={15}/></button></div><div className="floating-unit-list">{filtered.map(u=><article key={u.id}><div><button className="mini-unit-code" onClick={()=>openUnit(u)}>{u.code}</button><button className={'icon-button '+(favorites.has(u.id)?'is-favorite':'')} aria-label={`Yêu thích ${u.code}`} onClick={()=>onFavorite(u.id)}><Heart size={16} fill={favorites.has(u.id)?'currentColor':'none'}/></button></div><p>{u.type} · {fmt(u.area)} m²{!isGreen&&<> · Tầng {u.floor}</>}</p><div><strong>{fmt(u.price)} <small>tỷ</small></strong><span className={'status '+(statusOf(u)==='Còn hàng'?'available':'held')}>{statusOf(u)}</span></div><button className="mini-detail" onClick={()=>openUnit(u)}>Thông tin căn <ArrowUpRight size={15}/></button></article>)}{!filtered.length&&<div className="workspace-empty"><Search/><h3>Không có căn phù hợp</h3><button className="button subtle" onClick={reset}>Đặt lại bộ lọc</button></div>}</div><div className="floating-foot"><Info size={13}/>{isGreen?sourceStatus:units.some(u=>u.sourceLabel)?'Bảng hàng tham khảo · Chưa đồng bộ trực tiếp':'Quỹ căn và giá minh họa'}</div></aside>}{!listOpen&&<button className="reopen-list button dark" onClick={()=>setListOpen(true)}><List size={17}/>{filtered.length} căn</button>}
{((tab==='vr'&&vrScenes.length>1)||(tab==='plan'&&plans.length>0))&&<div className="scene-picker">{(tab==='vr'?vrScenes:plans).map((s,i)=><button className={scene===i?'active':''} key={s.id} onClick={()=>{setScene(i);setZoom(1);}}><img src={s.url} alt=""/><span>{s.name}</span></button>)}</div>}</>}
{!['vr','plan'].includes(tab)&&<section className={'workspace-panel'+(tab==='unitplan'?' is-unitplan':'')}><div className="workspace-panel-heading"><div><span>{project.name}</span><h1>{title}</h1></div><button className="round-tool" aria-label="Đóng nội dung" onClick={()=>changeTab('vr')}><X size={21}/></button></div><div className="workspace-panel-body">
{tab==='overview'&&<div className="wsz-overview">
<div className="wsz-hero" style={{backgroundImage:`url(${project.image})`}}><div className="wsz-hero-copy"><h2>{project.name}</h2><button className="wsz-btn" onClick={()=>changeTab('vr')}><span>Khám phá quỹ căn 360°</span><i><ArrowUpRight size={16}/></i></button></div><p className="wsz-hero-aside">{project.location} · {project.developer}</p>
<div className="wsz-stats">{[[units.length,'căn trong quỹ căn'],[units.filter(u=>statusOf(u)==='Còn hàng').length,'căn còn hàng'],[Array.from(new Set(units.map(u=>u.zone).filter(Boolean))).length,'phân khu']].map(([v,l])=><div key={String(l)}><strong>{v}<sup>+</sup></strong><span>{l}</span></div>)}</div></div>
<div className="wsz-section"><div className="wsz-head"><span className="wsz-eyebrow">KHÁM PHÁ DỰ ÁN</span><h3>Mọi thông tin bạn cần về {project.name}</h3><button className="wsz-btn is-ghost" onClick={()=>changeTab('inventory')}><span>Xem bảng hàng</span><i><ArrowUpRight size={16}/></i></button></div>
<div className="wsz-cols">{([['vr','Quỹ căn 360°','Bản đồ phối cảnh và vị trí từng căn trên dự án.',Globe],['plan','Mặt bằng','Mặt bằng tổng thể, mã căn ghim theo loại quỹ.',Map],['inventory','Bảng hàng','Giá, diện tích, hướng và trạng thái từng căn.',List],['amenity','Tiện ích','Hình ảnh tiện ích nội khu và kết nối vùng.',Waves]] as const).map(([k,t,d,Icon],i)=><button key={k} className="wsz-col" onClick={()=>changeTab(k)}><small>0{i+1}.</small><Icon size={34} strokeWidth={1.4}/><strong>{t}</strong><span>{d}</span><i><ArrowUpRight size={16}/></i></button>)}</div></div>
<div className="wsz-cta"><button className="wsz-cta-card is-photo" onClick={()=>changeTab('location')} style={{backgroundImage:`url(${project.image})`}}><strong>Vị trí & kết nối<br/>của dự án</strong><span className="wsz-btn"><span>Xem vị trí</span><i><ArrowUpRight size={16}/></i></span></button><button className="wsz-cta-card is-mint" onClick={()=>changeTab('gallery')}><strong>Khám phá hình ảnh<br/>và nhà mẫu</strong><span className="wsz-btn"><span>Mở thư viện</span><i><ArrowUpRight size={16}/></i></span></button></div>
<div className="wsz-who"><div className="wsz-who-left"><span className="wsz-eyebrow">THÔNG TIN DỰ ÁN</span><img src={project.image} alt={project.name}/><p>{project.status} · {project.category==='high'?'Cao tầng':'Thấp tầng'}. Liên hệ để nhận bảng giá và lịch tham quan.</p><a className="wsz-phone" href={`tel:${contact.phone}`}><i><ArrowUpRight size={18}/></i><span><small>Hotline / Zalo</small><b>{contact.phone}</b></span></a></div>
<div className="wsz-who-right"><h3>{project.name}</h3><p className="wsz-lead">{project.description}</p><div className="row"><button className="wsz-btn" onClick={()=>changeTab('inventory')}><span>Xem quỹ căn</span><i><ArrowUpRight size={16}/></i></button><button className="wsz-btn is-ghost" onClick={()=>onFavorite(project.id)}><span>{favorites.has(project.id)?'Đã yêu thích':'Lưu dự án'}</span><i><Heart size={16} fill={favorites.has(project.id)?'currentColor':'none'}/></i></button></div>
<div className="wsz-acc">{[['Chủ đầu tư',project.developer],['Địa chỉ',project.location],['Loại hình',project.category==='high'?'Cao tầng':'Thấp tầng'],['Trạng thái',project.status]].map(([k,v],i)=><details key={k} open={i===0}><summary>{k}<Plus size={18}/></summary><p>{v}</p></details>)}</div></div></div>
</div>}
{tab==='inventory'&&<><div className="workspace-table-tools"><div className="row"><span className="inventory-total">{filtered.length} căn phù hợp</span><Selector label="Tòa" value={tower} values={towers} onChange={setTower}/><Selector label="Tầng" value={floor} values={floors.map(String)} onChange={setFloor}/><Selector label="Trạng thái" value={status} values={Array.from(new Set(units.map(statusOf)))} onChange={setStatus}/></div><div className="row"><button className="button subtle" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={16}/>Bộ lọc {activeFilters>0&&`(${activeFilters})`}</button><button className="button subtle" onClick={()=>exportUnits(filtered)}><Download size={16}/>Xuất bảng hàng</button><button className="button subtle" onClick={()=>setMatrix(!matrix)}>{matrix?<List size={17}/>:<LayoutGrid size={17}/>} {matrix?'Dạng bảng':'Theo tầng'}</button></div></div><div className="sample-note"><Info size={14}/>{isGreen?'Dữ liệu đồng bộ Google Sheets Vịnh Tiên mỗi 60 giây.':units.some(u=>u.sourceLabel)?'Bảng hàng tham khảo tại thời điểm cập nhật. Giá và trạng thái cần xác nhận lại; chưa đồng bộ trực tiếp.':'Dữ liệu minh họa, chưa kết nối kho hàng chủ đầu tư.'} Nhấn mã căn để xem chi tiết.</div>{matrix?<Matrix/>:<div className="table-wrap"><UnitRows/></div>}{!filtered.length&&<div className="workspace-empty"><h3>Không tìm thấy sản phẩm</h3><button className="button subtle" onClick={reset}>Đặt lại bộ lọc</button></div>}</>}
{tab==='unitplan'&&<UnitPlanTab units={units} statusOf={statusOf}/>}
{tab==='location'&&<div className="wsz-location"><div className="wsz-loc-card"><span className="wsz-eyebrow">VỊ TRÍ DỰ ÁN</span><h3>{project.location}</h3><p>Tra cứu vị trí và tuyến đường đến {project.name}.</p><dl><div><dt>Khu vực</dt><dd>{project.region}</dd></div><div><dt>Chủ đầu tư</dt><dd>{project.developer}</dd></div></dl><a className="wsz-btn" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(project.name+' '+project.location)}`}><span>Mở Google Maps</span><i><ArrowUpRight size={16}/></i></a></div><div className="wsz-map"><iframe title={`Bản đồ ${project.name}`} loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(project.name+' '+project.location)}&output=embed`}/></div><img className="wsz-loc-photo" src={project.image} alt="Phối cảnh dự án"/></div>}
{tab==='zones'&&<><div className="wsz-head"><span className="wsz-eyebrow">PHÂN KHU</span><h3>Chọn phân khu để xem sản phẩm tương ứng</h3></div><div className="wsz-cols">{Array.from(new Set(units.map(u=>u.zone))).map((z,i)=><button key={z} className="wsz-col" onClick={()=>{setZone(z);changeTab('inventory');}}><small>{String(i+1).padStart(2,'0')}.</small><Layers size={34} strokeWidth={1.4}/><strong>{z}</strong><span>{units.filter(u=>u.zone===z).length} căn · {units.filter(u=>u.zone===z&&statusOf(u)==='Còn hàng').length} căn còn hàng</span><i><ArrowUpRight size={16}/></i></button>)}</div></>}
{['model','amenity','gallery','document'].includes(tab)&&<><div className="section-heading"><p className="muted">{tab==='document'?'Bảng giá, chính sách và tài liệu gắn với dự án.':tab==='amenity'?'Hình ảnh và thông tin tiện ích được tải lên cho dự án.':tab==='model'?'Khám phá hình ảnh nhà mẫu và không gian nội thất.':'Ảnh tổng thể và thư viện dự án.'}</p>{canManage&&<Link className="button subtle" href={`/admin/thu-vien?project=${encodeURIComponent(project.id)}`}><Upload size={16}/>Thêm nội dung</Link>}</div>{tab==='document'?<div className="wsz-docs">{pictureFiles.map((a,i)=><a key={a.id} href={a.url+'?download=1'}><small>{String(i+1).padStart(2,'0')}.</small><FileText size={34} strokeWidth={1.4}/><strong>{a.name}</strong><span>Tải tài liệu</span><i><Download size={16}/></i></a>)}</div>:pictureFiles.length>0&&<div className="wsz-strip">{pictureFiles.map(a=><button key={a.id} onClick={()=>setLightbox(a)}><img src={a.url} alt={a.name}/><span><MapPin size={14}/>{project.name}</span><strong>{a.name}</strong></button>)}</div>}{!pictureFiles.length&&<div className="workspace-empty"><Upload size={32}/><h3>Chưa có {title.toLowerCase()} được tải lên</h3><p>Thêm tài liệu của dự án tại Thư viện để hiển thị tại đây.</p>{canManage&&<Link href={`/admin/thu-vien?project=${encodeURIComponent(project.id)}`} className="button dark">Mở thư viện quản trị</Link>}</div>}</>}
</div></section>}
<div className="workspace-side-tools"><button className="round-tool" onClick={toggleFull} aria-label="Toàn màn hình">{fullscreen?<Minimize size={19}/>:<Maximize size={19}/>}</button>{tab==='plan'&&plans.length>0&&!usePlanBoard&&<><button className="round-tool" aria-label="Phóng to mặt bằng" onClick={()=>setZoom(Math.min(3,zoom+.25))}><Plus size={18}/></button><button className="round-tool" aria-label="Thu nhỏ mặt bằng" onClick={()=>setZoom(Math.max(.5,zoom-.25))}><Minus size={18}/></button><button className="round-tool" aria-label="Đặt lại mặt bằng" onClick={()=>setZoom(1)}><RotateCcw size={18}/></button></>}<button className="round-tool" aria-label="Chia sẻ dự án" onClick={()=>navigator.clipboard.writeText(window.location.origin+'/du-an/'+project.id).then(()=>toast.success('Đã sao chép liên kết dự án.')).catch(()=>toast.error('Không thể sao chép liên kết.'))}><ArrowUpRight size={19}/></button></div>
<div className="workspace-bottom"><button className="collapse-circle" aria-label={dockOpen?'Thu gọn menu dự án':'Mở thanh chức năng'} onClick={()=>setDockOpen(!dockOpen)}>{dockOpen?<ChevronDown size={17}/>:<ChevronUp size={17}/>}</button>{dockOpen&&<nav aria-label="Các mục của dự án" className="workspace-dock">{nav.map(([v,l,Icon])=><Link key={v} href={projectPath(project.id,v)} data-slot="tabs-trigger" data-state={tab===v?'active':'inactive'} aria-current={tab===v?'page':undefined}><Icon size={22}/><span>{l}</span></Link>)}</nav>}</div>
<Sheet open={filtersOpen} onOpenChange={setFiltersOpen}><SheetContent className="workspace-filter-sheet"><SheetHeader><SheetTitle>Bộ lọc quỹ căn</SheetTitle><SheetDescription>{project.name} · {filtered.length} căn phù hợp</SheetDescription></SheetHeader><div className="sheet-body stack"><Selector label="Phân khu" value={zone} onChange={setZone} values={Array.from(new Set(units.map(u=>u.zone)))}/><Selector label="Loại hình" value={type} onChange={setType} values={Array.from(new Set(units.map(u=>u.type)))}/><Selector label="Hướng" value={direction} onChange={setDirection} values={Array.from(new Set(units.map(u=>u.direction)))}/><Selector label="Trạng thái" value={status} onChange={setStatus} values={Array.from(new Set(units.map(statusOf)))}/><Selector label="Tòa" value={tower} onChange={setTower} values={towers}/><Selector label="Tầng" value={floor} onChange={setFloor} values={floors.map(String)}/><label className="field"><span>Giá: {fmt(price[0])} – {fmt(price[1])} tỷ</span><Slider aria-label="Khoảng giá dự án" min={0} max={150} value={price} step={.1} onValueChange={setPrice}/></label><label className="field"><span>Diện tích: {area[0]} – {area[1]} m²</span><Slider aria-label="Khoảng diện tích dự án" min={0} max={1000} value={area} onValueChange={setArea}/></label><label className="row"><Checkbox checked={savedOnly} onCheckedChange={v=>setSavedOnly(v===true)}/>Chỉ xem căn yêu thích</label><label className="field"><span>Sắp xếp</span><Select value={sort} onValueChange={setSort}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['code','Theo mã căn'],['price-up','Giá tăng dần'],['price-down','Giá giảm dần'],['area','Diện tích giảm dần']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><div className="row"><button className="button subtle" onClick={reset}><RotateCcw size={16}/>Đặt lại</button><button className="button dark" onClick={()=>{setFiltersOpen(false);setListOpen(true);}}>Xem {filtered.length} căn</button></div></div></SheetContent></Sheet>
<Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent side="left"><SheetHeader><img className="workspace-menu-logo" src={contact.logo} alt="Alpha HUB"/><SheetTitle>{project.name}</SheetTitle><SheetDescription>{project.location}</SheetDescription></SheetHeader><nav className="workspace-menu-links">{nav.map(([v,l,Icon])=><Link key={v} href={projectPath(project.id,v)} aria-current={tab===v?'page':undefined} className={tab===v?'active':''}><Icon size={19}/>{l}<ChevronRight size={16}/></Link>)}<Link href="/du-an"><ChevronLeft size={17}/>Danh sách dự án</Link><h3>Chuyển dự án</h3>{projects.map(p=><Link key={p.id} href={projectPath(p.id)} className={p.id===project.id?'active':''}><Building2 size={17}/>{p.name}</Link>)}</nav></SheetContent></Sheet>
<Dialog open={!!lightbox} onOpenChange={v=>{if(!v)setLightbox(null);}}><DialogContent className="workspace-lightbox"><DialogHeader><DialogTitle>{lightbox?.name}</DialogTitle><DialogDescription>{project.name}</DialogDescription></DialogHeader>{lightbox&&<><img src={lightbox.url} alt={lightbox.name}/><a className="button subtle" href={lightbox.url} target="_blank" rel="noreferrer">Mở ảnh gốc <ArrowUpRight size={17}/></a></>}</DialogContent></Dialog>
</div>;
}

/** "Mặt Bằng Căn": the Vịnh Tiên poster studio, restyled. Guests get a unit picker and the finished
 *  poster; administrators get the full editor (the studio shows its own panel when it is in admin mode). */
function UnitPlanTab({units,statusOf}:{units:Unit[];statusOf:(u:Unit)=>string}){
 const frame=useRef<HTMLIFrameElement>(null);
 const [admin,setAdmin]=useState<boolean|null>(null),[code,setCode]=useState(units[0]?.code||''),[q,setQ]=useState(''),[only,setOnly]=useState('all');
 const initial=useRef(new URLSearchParams(typeof window==='undefined'?'':window.location.search).get('product')||units[0]?.code||'');
 useEffect(()=>{const on=(e:MessageEvent)=>{if(e.origin!==window.location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='vinh-tien-mode')setAdmin(!!e.data.canEdit);if(e.data?.type==='vinh-tien-selected'&&e.data.code)setCode(e.data.code);};window.addEventListener('message',on);return()=>window.removeEventListener('message',on);},[]);
 const pick=(c:string)=>{setCode(c);frame.current?.contentWindow?.postMessage({type:'vinh-tien-select',code:c},window.location.origin);};
 const list=units.filter(u=>(only==='all'||statusOf(u)===only)&&u.code.toLowerCase().includes(q.trim().toLowerCase()));
 return <div className={'unitplan'+(admin?' is-admin':'')}>
  {!admin&&<aside className="unitplan-list"><div className="unitplan-list-head"><span className="wsz-eyebrow">DANH SÁCH MÃ CĂN</span><strong>{list.length}<small>/{units.length} mã</small></strong></div>
   <label className="unitplan-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm mã căn…" aria-label="Tìm mã căn"/></label>
   <div className="unitplan-chips">{['all','Còn hàng','Đã bán'].map(s=><button key={s} className={only===s?'is-on':''} onClick={()=>setOnly(s)}>{s==='all'?'Tất cả':s}</button>)}</div>
   <div className="unitplan-codes">{list.map(u=><button key={u.id} className={u.code===code?'is-on':''} onClick={()=>pick(u.code)}><span><b>{u.code}</b><small>{u.type||'Sản phẩm'}{u.area?' · '+u.area.toLocaleString('vi-VN')+' m²':''}</small></span><em>{u.price?u.price.toLocaleString('vi-VN',{maximumFractionDigits:2})+' tỷ':'Liên hệ'}</em></button>)}{!list.length&&<p className="muted">Không có mã phù hợp.</p>}</div>
   <p className="unitplan-note">Chọn mã căn để xem bảng thông tin và tải ảnh.</p></aside>}
  <div className="unitplan-stage">{admin===null&&<div className="unitplan-loading">Đang tải bảng thông tin…</div>}<iframe ref={frame} title="Mặt bằng căn Vịnh Tiên" src={'/vinh-tien-editor?embed=1&code='+encodeURIComponent(initial.current)}/></div>
 </div>;
}
