import {masteriAccountSnapshot} from './masteri-account-snapshot';
export type Project={id:string;name:string;location:string;region:string;developer:string;category:string;status:string;image:string;hot:boolean;description:string;lat:number;lng:number;};
export type Unit={tower?:string;id:string;code:string;projectId:string;category:string;zone:string;type:string;group:string;direction:string;area:number;builtArea:number;price:number;status:string;beds:number;floor:number;x:number;y:number;note:string;priceTts?:number|string;priceTttd?:number|string;priceLoan?:number|string;pricePerMeter?:number|string;totalPrice?:number|string;gift?:string;policyDate?:string;layoutUrl?:string;posterUrl?:string;sourceLabel?:string;sourceCheckedAt?:string;sourceUrl?:string;};
export type Customer={id:string;name:string;phone:string;email:string;note:string;stage:string;};
export type Article={id:string;title:string;category:string;body:string;date:string;image:string;};
export type Asset={id:string;projectId:string;kind:string;name:string;url:string;};
export type Settings={brand:string;phone:string;email:string;address:string;holdHours:number;notifications:boolean;profileName:string;};
export type Reservation={id:string;unit_id:string;customer_id:string;note:string;status:string;expires_at:number;created_at:number;};
const rows=[
['ha-long','Vinhomes Global Gate Hạ Long','Tuần Châu, Quảng Ninh','Quảng Ninh','1789714544076_14d8d57f','low',20.95,107.03],
['ocean-park','Vinhomes Ocean Park 2–3','Nghĩa Trụ, Hưng Yên','Hưng Yên','1790064367861_7c5b3be5','low',20.97,105.96],
['green-paradise','Vinhomes Green Paradise','Cần Giờ, TP. Hồ Chí Minh','TP. Hồ Chí Minh','1789715023704_e3fa7971','low',10.4,106.91],
['parkland','The Parkland – Imperia Ocean City','Vinhomes Ocean Park 2, Hưng Yên','Hưng Yên','1789715073931_cbbeb29d','high',20.98,105.97],
['royal-island','Vinhomes Royal Island','Thủy Nguyên, Hải Phòng','Hải Phòng','1789715047601_e5053b2c','low',20.95,106.65],
['grand-coast','Masteri Grand Coast','Văn Giang, Hưng Yên','Hưng Yên','1789715062551_09ff6b22','high',20.97,105.98],
['lumiere','Lumière Hanoi Seasons Garden','Nguyễn Trãi, Hà Nội','Hà Nội','1789715036360_fa6835bc','high',20.99,105.81],
['golden-city','Vinhomes Golden City','Dương Kinh, Hải Phòng','Hải Phòng','1789715088933_cbe10bf8','low',20.8,106.71],
['hai-van','Vinhomes Hải Vân Bay','Liên Chiểu, Đà Nẵng','Đà Nẵng','1789715100877_759862e2','low',16.13,108.12],
['global-gate','Vinhomes Global Gate','Đông Anh, Hà Nội','Hà Nội','1789715115338_54e92692','low',21.11,105.88],
['wonder-city','Vinhomes Wonder City','Đan Phượng, Hà Nội','Hà Nội','1789715135230_c2bffd18','low',21.1,105.69],
['magnolia','The Magnolia Private Residences','Long Biên, Hà Nội','Hà Nội','1789715155244_f2b2b721','high',21.05,105.89],
['trang-cat','Happy Home Tràng Cát','Hải An, Hải Phòng','Hải Phòng','1789715168146_472551ba','low',20.8,106.75],
['saigon-park','Vinhomes Sài Gòn Park','Hóc Môn, TP. Hồ Chí Minh','TP. Hồ Chí Minh','1789715178484_060be167','low',10.91,106.59],
];
export const seedProjects:Project[]=rows.map((r,i)=>({id:String(r[0]),name:String(r[1]),location:String(r[2]),region:String(r[3]),image:`https://pub-ab7903723e3a478281ffe6804313332e.r2.dev/tours/${r[4]}.webp`,category:String(r[5]),lat:Number(r[6]),lng:Number(r[7]),developer:[5,6].includes(i)?'Masterise Homes':i===3?'MIK Group':'Vinhomes',status:'Đang mở bán',hot:i<3||i===4,description:i===5?'Bảng hàng tham khảo được ghi nhận từ VHub ngày 27/09/2026. Giá và trạng thái cần được xác nhận lại; chưa đồng bộ trực tiếp.':'Dự án tham khảo từ danh mục công khai VHub. Các căn, giá và trạng thái trong bản trải nghiệm là dữ liệu minh họa, cần thay bằng bảng hàng chính thức trước khi giao dịch.'}));
const order=[2,1,13,0,4,10,3,5,6,7,8,9,11,12];
const projectUnitSeeds=order.filter((n)=>n!==5).flatMap((n)=>Array.from({length:8},(_,j)=>({id:`u-${n}-${j}`,code:`${['BM','VT','TL','PK','RI','GC','LM','GD','HV','GG','WC','MG','TC','AS'][n]}${String(j+1).padStart(2,'0')}-${String(12+j*2).padStart(2,'0')}`,projectId:seedProjects[n].id,category:seedProjects[n].category,zone:['Ánh Dương','Bình Minh','Hoàng Hôn'][j%3],type:seedProjects[n].category==='high'?['Studio','1 phòng ngủ','2 phòng ngủ','3 phòng ngủ'][j%4]:['Liền kề','Shophouse','Biệt thự song lập','Biệt thự đơn lập'][j%4],group:j%3===0?'Quỹ độc quyền':'Quỹ chủ đầu tư',direction:['Đông Nam','Tây Bắc','Đông Bắc','Tây Nam'][j%4],area:seedProjects[n].category==='high'?35+j*11:[80,100,150,250][j%4],builtArea:seedProjects[n].category==='high'?38+j*12:240+j*18,price:Number((seedProjects[n].category==='high'?2.15+j*.64:6.85+j*1.35+n*.15).toFixed(3)),status:j===7?'Đã bán':'Còn hàng',beds:1+j%4,floor:seedProjects[n].category==='high'?5+j:4,x:15+(j%4)*22,y:30+Math.floor(j/4)*35,note:'Căn mẫu để trải nghiệm bộ lọc và quy trình giữ chỗ. Không phải báo giá hoặc cam kết bán hàng.'})));
export const seedUnits:Unit[]=[...projectUnitSeeds,...masteriAccountSnapshot];

export const seedArticles:Article[]=[
{id:'tra-cuu',title:'Tra cứu quỹ căn: từ nhu cầu đến danh sách phù hợp',category:'Hướng dẫn',date:'2026-09-22',image:seedProjects[2].image,body:'Bắt đầu từ loại hình thấp tầng hoặc cao tầng. Chọn dự án, phân khu và khoảng ngân sách, sau đó nhấn Tìm kiếm.\n\nMỗi thẻ căn hiển thị diện tích, hướng và giá tham khảo. Mở chi tiết để xem đầy đủ thông tin. Lưu các căn quan tâm vào danh sách yêu thích hoặc thêm tối đa ba căn để so sánh.\n\nGiá trong bản trải nghiệm là dữ liệu mẫu. Hãy xác nhận bảng giá và trạng thái thực tế với đơn vị phân phối trước khi đưa ra quyết định.'},
{id:'quy-trinh',title:'Quản lý giữ chỗ và theo dõi khách hàng trên một nền tảng',category:'Nghiệp vụ',date:'2026-09-21',image:seedProjects[1].image,body:'Tạo hồ sơ khách hàng trước khi giữ chỗ. Tại chi tiết căn, chọn khách hàng, nhập ghi chú và xác nhận giữ chỗ.\n\nHệ thống ghi nhận giao dịch và thời hạn. Vào mục Giao dịch để gia hạn, hủy hoặc chuyển trạng thái đã bán. Giữ chỗ trên website này chỉ có hiệu lực trong hệ thống riêng của bạn, không liên kết với chủ đầu tư.\n\nThời hạn giữ chỗ mặc định có thể thay đổi tại Cấu hình.'},
{id:'du-lieu',title:'Chuẩn bị dữ liệu dự án, mặt bằng và ảnh 360°',category:'Nền tảng',date:'2026-09-20',image:seedProjects[0].image,body:'Mỗi dự án có thể bổ sung ảnh thư viện, mặt bằng, tài liệu PDF và ảnh panorama.\n\nẢnh panorama cần định dạng cầu 360° equirectangular tỷ lệ 2:1. Mặt bằng có thể gắn vị trí căn thông qua tọa độ phần trăm X và Y trong phần chỉnh sửa căn.\n\nChỉ tải lên tài liệu bạn được phép sử dụng. Các tài liệu tải lên được lưu cùng dự án và có thể mở hoặc tải xuống từ trang chi tiết.'}
];
export const defaultSettings:Settings={brand:'Alpha Hub',phone:'0343977651',email:'',address:'',holdHours:24,notifications:true,profileName:''};
export const guides=[['Tra cứu và tìm kiếm quỹ căn','Chọn Thấp tầng hoặc Cao tầng, nhập mã căn hoặc chọn bộ lọc. Nhấn Tìm kiếm để áp dụng. Nhấn Đặt lại để bỏ mọi điều kiện.'],['Xem mặt bằng và quỹ căn 360°','Mở Dự án → chọn dự án → Mặt bằng hoặc Quỹ căn 360°. Mặt bằng và ảnh panorama cần được tải lên tại Thư viện quản trị. Nhấn điểm đánh dấu trên mặt bằng để mở căn.'],['Giữ chỗ và đặt căn cho khách hàng','Tạo hồ sơ tại Khách hàng. Mở một căn còn hàng, chọn Giữ chỗ, chọn khách và xác nhận. Giao dịch được lưu theo tài khoản của bạn; hệ thống không thu tiền và không gửi giữ chỗ tới chủ đầu tư.'],['Quản lý khách hàng và giao dịch','Khách hàng cho phép thêm, sửa thông tin liên hệ và giai đoạn chăm sóc. Giao dịch cho phép xem thời hạn, gia hạn, hủy giữ chỗ hoặc chuyển thành đã bán.'],['Lưu căn và dự án yêu thích','Nhấn biểu tượng trái tim trên thẻ căn hoặc dự án. Danh sách được lưu theo tài khoản và xem lại trong Yêu thích.'],['So sánh sản phẩm bất động sản','Nhấn biểu tượng so sánh trên các căn, tối đa 3 căn. Mở thanh So sánh để xem giá, diện tích, hướng, loại hình và trạng thái cạnh nhau.'],['Tải bảng giá và tài liệu dự án','Nhấn Xuất bảng hàng để tải CSV theo kết quả lọc hiện tại. Tại dự án, mở Tài liệu để tải các file đã được quản trị viên đưa lên.'],['Cấu hình và tài khoản cá nhân','Trong Cấu hình, thay tên nền tảng, thông tin liên hệ và thời hạn giữ chỗ. Bản riêng tư hiện sử dụng tài khoản ChatGPT và dữ liệu tách biệt theo người dùng.'],['Nhập và quản lý quỹ căn','Trong Quản lý quỹ căn, thêm hoặc sửa từng căn, hoặc tải file CSV UTF-8 theo mẫu. Kiểm tra dữ liệu trước khi xác nhận nhập.'],['Thông báo cập nhật','Mở biểu tượng chuông để xem các thao tác giữ chỗ và thay đổi gần đây của tài khoản. Có thể đánh dấu tất cả đã đọc.']];
