// Snapshot of the inventory visible in the owner's VHub account on 2026-09-27T10:42:39.244Z.
// This is a point-in-time reference, not a live feed or a sales guarantee.
import type {Unit} from './catalog';
export const masteriAccountSnapshot:Unit[]=[
  {
    "id": "vhub-c5l1-10-18a",
    "code": "C5L1-10-18A",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L1",
    "type": "3 Phòng ngủ",
    "group": "Quỹ độc quyền",
    "direction": "Tây Nam",
    "area": 106.4,
    "builtArea": 0,
    "price": 7.55,
    "status": "Còn hàng",
    "beds": 3,
    "floor": 10,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l1-21-02",
    "code": "C5L1-21-02",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L1",
    "type": "2 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Tây Nam",
    "area": 72.8,
    "builtArea": 0,
    "price": 5.162,
    "status": "Còn hàng",
    "beds": 2,
    "floor": 21,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l1-22-06",
    "code": "C5L1-22-06",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L1",
    "type": "1 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Đông Bắc",
    "area": 46.3,
    "builtArea": 0,
    "price": 3.058,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 22,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l1-23-09",
    "code": "C5L1-23-09",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L1",
    "type": "1 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Đông Bắc",
    "area": 47.5,
    "builtArea": 0,
    "price": 3.152,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 23,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l2-20-10",
    "code": "C5L2-20-10",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L2",
    "type": "1 Phòng ngủ",
    "group": "Quỹ độc quyền",
    "direction": "Đông Bắc",
    "area": 42.7,
    "builtArea": 0,
    "price": 2.935,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 20,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l2-21-10",
    "code": "C5L2-21-10",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L2",
    "type": "1 Phòng ngủ",
    "group": "Quỹ độc quyền",
    "direction": "Đông Bắc",
    "area": 42.7,
    "builtArea": 0,
    "price": 2.915,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 21,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l2-22-08",
    "code": "C5L2-22-08",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L2",
    "type": "Studio",
    "group": "Quỹ độc quyền",
    "direction": "Đông Bắc",
    "area": 31.2,
    "builtArea": 0,
    "price": 2.179,
    "status": "Còn hàng",
    "beds": 0,
    "floor": 22,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l2-25-03",
    "code": "C5L2-25-03",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "L2",
    "type": "1 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Chưa cập nhật",
    "area": 47.8,
    "builtArea": 0,
    "price": 3.518,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 25,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5l3-07-12",
    "code": "C5L3-07-12",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Sand",
    "tower": "L3",
    "type": "1 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Chưa cập nhật",
    "area": 47.5,
    "builtArea": 0,
    "price": 3.041,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 7,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5z1-06-11",
    "code": "C5Z1-06-11",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "Z1",
    "type": "3 Phòng ngủ",
    "group": "Quỹ độc quyền",
    "direction": "Đông Bắc",
    "area": 92.8,
    "builtArea": 0,
    "price": 6.116,
    "status": "Còn hàng",
    "beds": 3,
    "floor": 6,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5z1-07-01",
    "code": "C5Z1-07-01",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "Z1",
    "type": "2 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Chưa cập nhật",
    "area": 70,
    "builtArea": 0,
    "price": 4.529,
    "status": "Còn hàng",
    "beds": 2,
    "floor": 7,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  },
  {
    "id": "vhub-c5z1-16-18",
    "code": "C5Z1-16-18",
    "projectId": "grand-coast",
    "category": "high",
    "zone": "The Wave",
    "tower": "Z1",
    "type": "1 Phòng ngủ+",
    "group": "Quỹ độc quyền",
    "direction": "Tây Bắc",
    "area": 49,
    "builtArea": 0,
    "price": 3.236,
    "status": "Còn hàng",
    "beds": 1,
    "floor": 16,
    "x": 50,
    "y": 50,
    "note": "Nhập từ bảng hàng hiển thị trong tài khoản theo yêu cầu chủ website; chưa xác minh trạng thái với đơn vị phân phối.",
    "sourceLabel": "Bảng hàng VHub",
    "sourceCheckedAt": "2026-09-27T10:42:39.244Z",
    "sourceUrl": "https://vhub.com.vn/du-an/masteri-grand-coast/bang-hang"
  }
];

